// Generated by scripts/generate-f2l-scramble-pool.mts. Do not edit by hand;
// run `npm run generate:scrambles` instead.
//
// Short setup scrambles per F2L case, applied to a cube whose first two layers
// are solved (the last layer does not matter). Each one places the pair into
// the case without being the inverse of a known algorithm for that case.
// Last-layer pieces end up wherever the search left them.

import type { F2LId } from '@/types/f2l';

export const F2L_SCRAMBLE_POOL: Record<F2LId, readonly string[]> = {
  'F2L-1': ["F' L' U L F U'", "F' U' L' U2 L U' F U'", "R U R' U R U' R' U'", "R' U' R F R' F' U R", "L F' U L F' L' F2 U' L'", "L R U' R' U L' R U R'", "R B U2 B' R' U2 R U R'", "R U2 R' F' U2 F R U' R'", "R' D R2 U2 R' U2 R2 D' R2"],
  'F2L-2': ["F' U2 F U2", "R B' R B R2 U2", "B U2 F' U' F U2 B' U'", "F U2 F2 U' F2 U' F' U2", "F' L U L' F L U' L'", "F' U' F U' R U' R' U'", "R B' R B R' U' R' U'", "F R F' U' F' U F U' R'", "F' U' F L U F U' F' L'", "F' U2 F2 U F' U F U2 F'", "R2 B' R' B U2 B U2 B' R'"],
  'F2L-3': ["R U2 B U B' R' U2", "B' F' U F2 U' B U F'", "F' U2 F U2 R U2 R' U'", "L' U2 F' U' F U' L U'", "R2 B' R' B2 U2 B' U R'", "F' U' F' L' U' L U F2 U2", "F2 U' F' U' F U F U F2", "R U' B U2 B2 R B R2 U2", "R' F R F2 U F R U R'"],
  'F2L-4': ["F' U2 L' U' L F U2", "L F' L' U L F L' U2", "L R U' R2 U L' U' R", "R U B' R B R' U2 R'", "R' F' U' F U R2 U' R'", "F' U F' L F L' U' F U'", "L U' R' U L' U' R2 U' R'", "R' U' R U' R' U2 R2 U' R'"],
  'F2L-5': ["R U2 B U' B' R' U2", "F2 L F2 L' U' L' U L", "R2 U2 F R F' U2 R2 U'", "L U F2 U' L' U L F2 L'", "R B U2 B' U B U2 B' R'", "R2 U2 F R' F' U2 R' U R'"],
  'F2L-6': ["R2 U B U' B' R2", "F' U2 L' U L F U2", "F' U L' U' L U F U'", "F' U2 F U' F' U F U'", "R' U' F R F' R' U R", "R2 B' R2 B U B U' B'", "L' F' U' L U2 L' U' F L", "R B' U' R' U R B R' U'", "R' U' R' F R2 F' R' U R"],
  'F2L-7': ["F2 U2 R' F2 R U2 F2", "L F' U F2 U' F' L'", "R U' B U2 B' U' R'", "R U2 B U2 B' U' R' U'", "D R2 U2 R' U R U R2 D'", "F R' F' D' R U2 R' D R", "L2 F2 L' U2 L' U2 L2 F2 L2", "R B2 R' U2 R U2 R B2 R2", "R F R U R' U' F' R' U'"],
  'F2L-8': ["B' R U' R2 U R B", "F' U L' U2 L U F", "R2 U2 F R2 F' U2 R2", "F' U L' U' L U2 F U'", "F' U2 F U' F' U2 F U'", "D' F2 U2 F U' F' U' F2 D", "L' F U2 F2 U2 F' L2 F2 L'", "R2 F2 U2 F R2 F' U2 F2 R2", "R2 U R' B' R B2 U' B' R2"],
  'F2L-9': ["R2 B U B' U' R2", "F' U2 L' U L U' F", "F' U F U F' U F U'", "F' U F U2 R U' R' U'", "F2 D' F' D F' R2 U' R2", "R2 B' R' B2 U' B' U R'", "F' U F2 D F' U F D' F'", "F' U' F2 U' B' U F' U' B", "F' U2 F L F' U F U' L'", "F' U2 R' U' R F R' U R", "R2 U B U' B' R' U' R' U2"],
  'F2L-10': ["F2 L' U' L U F2", "R U2 B U' B' U R'", "F' U2 L' U' L U F U", "R U' R' U F' U' F U'", "L' F L2 U2 F U2 L2 F' L", "R U R2 U L U' R U L'", "R U' R D R' U' R D' R2", "R U' R' F R' F' R2 U' R'", "R U' R' U' R2 B' R' B R'"],
  'F2L-11': ["F U F2 U F2 U2 F'", "F U2 F' U' F' U F2 U2 F'", "F' R' U2 R U F R' U R", "L' U' L2 F' L' U F2 U2 F'", "R' F D' F D F2 R2 U2 R'", "R2 B2 R2 B' U B R2 B2 R2"],
  'F2L-12': ["R U2 B U2 B' U R'", "R U' R' U F' U2 F U'", "R' D' F2 U' F2 D U R", "F' U F' L F L' U F U'", "R F R U R' U' F' U2 R'", "R U R U R' U R U2 R2", "R' U2 B' R2 B U2 R2 U' R'"],
  'F2L-13': ["F' U F U F' U' F U'", "F' U F2 R' F' R2 U' R'", "F2 D' F U F' D F2 U'", "R2 B' R' B2 U B' U R'", "F' R' U' R F2 R' F' U R", "F' U F2 D F' U' F D' F'", "L U F2 U' F U F2 U' L'", "R' B2 U2 B' R' B U2 B2 R"],
  'F2L-14': ["F2 L F L2 U' L U' F", "R2 B' R2 U' R U B R'", "F L2 U2 L F L' U2 L2 F'", "R F U R' U' R F' U' R'", "R U' R2 D' R U R' D R", "R' U2 B' R B U2 R2 U' R'"],
  'F2L-15': ["F' U2 L' U' L U' F", "R U' B U' B' U2 R'", "F' U L' U' L2 F' L' F2", "R U2 R B' R' B U' R'", "L F' U2 L' U' L U' F L'", "R2 B' R' B R' U' R U2 R'", "R2 U R2 U R2 U2 R' U R'"],
  'F2L-16': ["F' U L' U L U2 F", "R U2 B U B' U R'", "F' U2 F' L F L' U F", "R U' B U B2 R B R2", "F2 U' F2 U' F2 U2 F U' F", "L F' U L' U L U2 F L'", "R F U R U' R' F' R' U'", "R U R' U2 R B' R B R2", "R' D' F2 U' F U F D R"],
  'F2L-17': ["R2 U2 F R' F' U2 R2 U2", "B' R U' R' U B R U2 R'", "F' U2 F R U2 R2 F R F'", "L2 F2 L' F U2 F' L F2 L2"],
  'F2L-18': ["F2 U2 R' F R U2 F2 U2", "F2 L2 F U' L2 U F' L2 F2", "R B' U' R' U R B U2 R'", "R U2 R' F' U2 F2 R' F' R"],
  'F2L-19': ["R2 B' R' B U' R' U'", "F2 L F L2 U' L U F U", "R2 U2 R' U' R U' R' U R'", "L R U' R' U L' R U' R' U'", "L' U2 L F2 L F2 L2 U2 L U'", "R U' R' U2 R B U B' U R'", "R' U2 R' U R' U' R U2 R U2", "R2 U2 R' U2 R' U F R F' R'"],
  'F2L-20': ["F2 L F L' U F U", "R' F R F2 U2 F U", "F' L' U2 L2 F' L' F2 U'", "F' U2 F U2 F' U2 F U", "F' U' L F L' U2 L' U2 L", "F2 U2 F U F' U F U' F", "R' F2 R U' F' U R' F2 R", "R2 B' R' B2 U B' U' R' U'"],
  'F2L-21': ["L U' F2 U' F2 U F2 L'", "L U F' U' F2 U F' U' L'", "R B U' B' U' B U' B' R'", "R U' R2 F R F' R U' R'", "R' D' R U R' D R2 U2 R'", "R' U L U' R2 U L' U R'"],
  'F2L-22': ["F' U F R U' R' U2", "F' U F U2 F' U' F", "F' U' B U' F U B' U'", "F' U2 F U2 F' U F U2", "L' U F' U F U2 L U'", "R' F D' F D F2 R U'", "R2 B' R' B2 U2 B' R' U2", "F U2 F U' F2 U F' U2 F'", "L U F' U' L' U' L F L'", "R F U R U' R' F' U2 R'", "R U' B U' B2 R B R2 U'"],
  'F2L-23': ["F2 L F L2 U L F U2", "R U2 B' R B R' U' R'", "F2 L' U' L U F U F U2", "L' U R2 U' L U R' U R'", "R U' R' F' U' F R U' R'", "R U' R' U' R B U' B' R'"],
  'F2L-24': ["F2 U' F U' F' U2 F2 U2", "R2 B' R' B2 U' B' R' U2", "F' U F U F R' F' R U", "F' U2 F2 U2 F' U' F U' F'", "L2 F U L' F2 L U' F' L2", "R2 B' R' B2 U' B' U' R' U'"],
  'F2L-25': ["F U2 L F L' U2 F'", "R' U2 B' R B U2 R", "F' U2 L' U' L U2 F U'", "R F U R' U' R F' R'", "R2 U B' R' B R U' R2", "L F U2 L F L' F' U2 L'", "R2 U B' U' R' U B U' R'", "R2 U R' U R' U' R2 U' R2", "R2 U2 F R F' U2 R' U' R'"],
  'F2L-26': ["L F2 U F' U' F2 L'", "R' U2 B' R' B U2 R", "B' R2 U' R2 U R2 B U2", "F' R' U' R F R' U R", "F' U2 L' U L U2 F U'", "F U F U F' U' F' U' F'", "F' L U F' L' F2 L U' L'", "R U' B' U' R' U R2 B R2", "R2 U R' F D R' D' F' R'", "R2 U R2 F' U F R2 U' R2"],
  'F2L-27': ["F R' F' R2 U R'", "R2 B' R' B U2 R'", "F' L F' L' F U2 F", "F R' F' R U2 F' U2 F", "R U' B U' B' U' R' U2", "R U2 L U' R' U L' U2", "L F2 L' F U2 F2 U2 F' U2", "L R U' R' U L' R U2 R'", "R B U2 B' R' U2 R U2 R'", "R U R2 D' R U' R' D R", "R U' R' F' U F R U2 R'"],
  'F2L-28': ["F' U2 F R U2 R'", "F2 L F L' U2 F", "F' U2 F U2 F' U' F", "R B' R B R' U2 R'", "F' U2 B' U F U' B U2", "F' U2 F' L F L' F U2", "B F' U' F U B' F' U' F", "F R F' U2 F' U2 F U2 R'", "F' U' F L U F' U' F L'", "F' U2 F2 D F' U2 F D' F'", "R B' R B R2 U' R U' R'"],
  'F2L-29': ["F' L' U2 L U' F U'", "F' U F U' F' U F", "F' U F2 R' F' R U'", "F' U F U2 F' U2 F U'", "F' U' L' U' L U' F U'", "F' U B F U' F' U B' F", "F' U2 L' U L2 F' L' F2 U", "R U' R B' R' B2 U B' R'", "R2 U2 R2 U' F D' F D F2"],
  'F2L-30': ["B' R U' R' U B R U' R'", "F2 L F L2 U2 L U2 F U2", "F2 U2 F2 U R' D R' D' R2", "R U' L' R' U R U' L R'"],
  'F2L-31': ["F' U2 F R U R'", "F' L' U L2 F' L' F2", "R B' R B R' U R'", "F2 L F L2 U' L F U2", "R U B U2 B2 R B R2", "R' F R F' U R U2 R'", "L U L F2 L' F U' F L'", "R B' R B R2 U' R U2 R'", "R' F R F2 U' F R U' R'"],
  'F2L-32': ["F2 U2 F2 U F2 U F2", "F2 U' F2 U' F2 U2 F2 U2", "R U' B U2 B' U R' U'", "R2 U R2 U R2 U2 R2 U2", "D2 B2 U' B2 U' B2 U2 B2 D2", "D2 L2 U L2 U L2 U2 L2 D2", "F2 U' L U L' F2 L U' L'", "L' D2 U' B' U B D2 L U'", "R B2 U2 R B R' U2 B2 R'", "R2 U2 R2 U2 R' F R2 F' R'"],
  'F2L-33': ["B' D B U B' D' B", "F' L' U2 L U2 F U", "L' D2 L U2 L' D2 L", "R U2 B U2 B' R' U2", "B' D B U2 B' D' B U'", "F D F' U F D' F' U'", "F' U F U F' U2 F U'", "L' D2 L U' L' D2 L U'", "R U L U' R' U L' U'", "R U2 B U' B' U' R' U'", "B D2 U B' U B D2 U2 B'", "F2 U2 F' D' F U2 F' D F'"],
  'F2L-34': ["B D2 B' U2 B D2 B'", "F' U2 L' U2 L F U2", "L D' L' U' L D L'", "R B U2 B' U2 R' U'", "B D2 B' U' B D2 B' U'", "F' U L' U' L U' F U'", "F' U2 F U' F' U' F U'", "L D' L' U L D L' U2", "B D2 U2 B' U' B D2 U' B'", "F L2 U F' U F U2 L2 F'", "F2 U' F U' F' U2 F U' F", "L U L D' L' U' L D L2"],
  'F2L-35': ["F' U2 F U2 R U' R' U2", "R U' R B' R' B R' U", "F' U F U2 R' F R F' U2", "F' U2 L F' L2 U' L U F2", "R U' R' U R B U B' R'"],
  'F2L-36': ["F' U F' L F L' F U'", "F R' D R' D' R F' R U'", "F' U2 F' L' U' L U F2 U", "R' U2 B' R' B U2 R2 U' R'"],
  'F2L-37': ["R2 U2 F R2 F' U2 R' U R'", "B' R U' R2 U R B R U R'", "F' U F L F U F2 U' F L'", "R2 U R' U' R' U2 F R F' R'"],
  'F2L-38': ["F2 U2 F U F' U F U2 F", "R2 U2 F R' F' U2 R' U2 R'", "B F2 U B' U B U2 B' U2 F2", "L R U L' U L U2 L' U2 R'", "R U2 B U' B' R' U2 R U R'"],
  'F2L-39': ["F' U2 F' U' F U' F' U2 F2", "F R' F' R2 U2 R' U' R U R'", "F2 U2 B U2 B' U' B U' B' F2", "R U' R' U2 R B U B' U2 R'", "R U2 L U2 L' U' L U' L' R'"],
  'F2L-40': ["F' U2 L' U' L2 F' L' F2", "R2 B' R' B2 U' B' U2 R'", "F2 D' F' D2 R' D' R2 F' R'", "R U F R U R' U' F' R'"],
  'F2L-41': ["F2 L' U' L U F U' F", "R U' R U B U' B' R2", "R F U R U' R' F' U' R'", "L F2 L' U' L U F U' F L'", "R2 U R' U R U2 B' R' B R'", "R2 U R2 F R F2 U F U2 R'"],
};
